/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.api;

import fr.jbwittner.blizzardswagger.wowretailapi.ApiException;
import fr.jbwittner.blizzardswagger.wowretailapi.model.ArrayAssetDTO;
import fr.jbwittner.blizzardswagger.wowretailapi.model.ArrayCovenantIndexDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CovenantApiApi
 */
@Ignore
public class CovenantApiApiTest {

    private final CovenantApiApi api = new CovenantApiApi();

    
    /**
     * 
     *
     * Returns an index of covenants.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCovenantIndexTest() throws ApiException {
        String namespace = null;
        String region = null;
        String locale = null;
        ArrayCovenantIndexDTO response = api.getCovenantIndex(namespace, region, locale);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns media for a covenant by ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCovenantMediaByIdTest() throws ApiException {
        String namespace = null;
        String region = null;
        Integer covenantId = null;
        String locale = null;
        ArrayAssetDTO response = api.getCovenantMediaById(namespace, region, covenantId, locale);

        // TODO: test validations
    }
    
}
