/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.api;

import fr.jbwittner.blizzardswagger.wowretailapi.ApiException;
import fr.jbwittner.blizzardswagger.wowretailapi.model.ArraySpecializationsIndexData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.PlayableClassRaceMediaData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.PlayableSpecializationData;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlayableSpecializationApi
 */
@Ignore
public class PlayableSpecializationApiTest {

    private final PlayableSpecializationApi api = new PlayableSpecializationApi();

    
    /**
     * 
     *
     * Returns a playable specialization by ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlayableSpecializationByIdTest() throws ApiException {
        String namespace = null;
        String region = null;
        Integer specId = null;
        String locale = null;
        PlayableSpecializationData response = api.getPlayableSpecializationById(namespace, region, specId, locale);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns an index of playable specializations.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlayableSpecializationIndexTest() throws ApiException {
        String namespace = null;
        String region = null;
        String locale = null;
        ArraySpecializationsIndexData response = api.getPlayableSpecializationIndex(namespace, region, locale);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns media for a playable specialization by ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlayableSpecializationMediaByIdTest() throws ApiException {
        String namespace = null;
        String region = null;
        Integer specId = null;
        String locale = null;
        PlayableClassRaceMediaData response = api.getPlayableSpecializationMediaById(namespace, region, specId, locale);

        // TODO: test validations
    }
    
}
