/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.api;

import fr.jbwittner.blizzardswagger.wowretailapi.ApiException;
import fr.jbwittner.blizzardswagger.wowretailapi.model.ArrayClassesIndexDTO;
import fr.jbwittner.blizzardswagger.wowretailapi.model.PlayableClassDTO;
import fr.jbwittner.blizzardswagger.wowretailapi.model.PlayableClassRaceMediaDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlayableClassApiApi
 */
@Ignore
public class PlayableClassApiApiTest {

    private final PlayableClassApiApi api = new PlayableClassApiApi();

    
    /**
     * 
     *
     * Returns a playable class by ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlayableClassByIdTest() throws ApiException {
        String namespace = null;
        String region = null;
        Integer classId = null;
        String locale = null;
        PlayableClassDTO response = api.getPlayableClassById(namespace, region, classId, locale);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns an index of playable classes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlayableClassIndexTest() throws ApiException {
        String namespace = null;
        String region = null;
        String locale = null;
        ArrayClassesIndexDTO response = api.getPlayableClassIndex(namespace, region, locale);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns media for a playable class by ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlayableClassMediaByIdTest() throws ApiException {
        String namespace = null;
        String region = null;
        Integer classId = null;
        String locale = null;
        PlayableClassRaceMediaDTO response = api.getPlayableClassMediaById(namespace, region, classId, locale);

        // TODO: test validations
    }
    
}
