/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.IndexData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Array of races index
 */
@ApiModel(description = "Array of races index")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ArrayRacesIndexData {
  public static final String SERIALIZED_NAME_RACES = "races";
  @SerializedName(SERIALIZED_NAME_RACES)
  private List<IndexData> races = new ArrayList<>();

  public ArrayRacesIndexData() { 
  }

  public ArrayRacesIndexData races(List<IndexData> races) {
    
    this.races = races;
    return this;
  }

  public ArrayRacesIndexData addRacesItem(IndexData racesItem) {
    this.races.add(racesItem);
    return this;
  }

   /**
   * Get races
   * @return races
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<IndexData> getRaces() {
    return races;
  }


  public void setRaces(List<IndexData> races) {
    this.races = races;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArrayRacesIndexData arrayRacesIndexData = (ArrayRacesIndexData) o;
    return Objects.equals(this.races, arrayRacesIndexData.races);
  }

  @Override
  public int hashCode() {
    return Objects.hash(races);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArrayRacesIndexData {\n");
    sb.append("    races: ").append(toIndentedString(races)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

