/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.GenderNameDTO;
import fr.jbwittner.blizzardswagger.wowretailapi.model.IndexDTO;
import fr.jbwittner.blizzardswagger.wowretailapi.model.NameDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Playable class data
 */
@ApiModel(description = "Playable class data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-06T22:01:26.900029+02:00[Europe/Paris]")
public class PlayableClassDTO {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private NameDTO name;

  public static final String SERIALIZED_NAME_GENDER_NAME = "gender_name";
  @SerializedName(SERIALIZED_NAME_GENDER_NAME)
  private GenderNameDTO genderName;

  public static final String SERIALIZED_NAME_POWER_TYPE = "power_type";
  @SerializedName(SERIALIZED_NAME_POWER_TYPE)
  private IndexDTO powerType;

  public static final String SERIALIZED_NAME_SPECIALIZATIONS = "specializations";
  @SerializedName(SERIALIZED_NAME_SPECIALIZATIONS)
  private List<IndexDTO> specializations = new ArrayList<IndexDTO>();


  public PlayableClassDTO id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Id of the class
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Id of the class")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public PlayableClassDTO name(NameDTO name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public NameDTO getName() {
    return name;
  }


  public void setName(NameDTO name) {
    this.name = name;
  }


  public PlayableClassDTO genderName(GenderNameDTO genderName) {
    
    this.genderName = genderName;
    return this;
  }

   /**
   * Get genderName
   * @return genderName
  **/
  @ApiModelProperty(required = true, value = "")

  public GenderNameDTO getGenderName() {
    return genderName;
  }


  public void setGenderName(GenderNameDTO genderName) {
    this.genderName = genderName;
  }


  public PlayableClassDTO powerType(IndexDTO powerType) {
    
    this.powerType = powerType;
    return this;
  }

   /**
   * Get powerType
   * @return powerType
  **/
  @ApiModelProperty(required = true, value = "")

  public IndexDTO getPowerType() {
    return powerType;
  }


  public void setPowerType(IndexDTO powerType) {
    this.powerType = powerType;
  }


  public PlayableClassDTO specializations(List<IndexDTO> specializations) {
    
    this.specializations = specializations;
    return this;
  }

  public PlayableClassDTO addSpecializationsItem(IndexDTO specializationsItem) {
    this.specializations.add(specializationsItem);
    return this;
  }

   /**
   * Get specializations
   * @return specializations
  **/
  @ApiModelProperty(required = true, value = "")

  public List<IndexDTO> getSpecializations() {
    return specializations;
  }


  public void setSpecializations(List<IndexDTO> specializations) {
    this.specializations = specializations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayableClassDTO playableClassDTO = (PlayableClassDTO) o;
    return Objects.equals(this.id, playableClassDTO.id) &&
        Objects.equals(this.name, playableClassDTO.name) &&
        Objects.equals(this.genderName, playableClassDTO.genderName) &&
        Objects.equals(this.powerType, playableClassDTO.powerType) &&
        Objects.equals(this.specializations, playableClassDTO.specializations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, genderName, powerType, specializations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayableClassDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    genderName: ").append(toIndentedString(genderName)).append("\n");
    sb.append("    powerType: ").append(toIndentedString(powerType)).append("\n");
    sb.append("    specializations: ").append(toIndentedString(specializations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

