/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.IndexData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.PvpSpellDescritpionData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PVP Talent tiers data
 */
@ApiModel(description = "PVP Talent tiers data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PvpTalentTiersData {
  public static final String SERIALIZED_NAME_TALENT = "talent";
  @SerializedName(SERIALIZED_NAME_TALENT)
  private IndexData talent;

  public static final String SERIALIZED_NAME_SPELL_TOOLTIP = "spell_tooltip";
  @SerializedName(SERIALIZED_NAME_SPELL_TOOLTIP)
  private PvpSpellDescritpionData spellTooltip;

  public PvpTalentTiersData() { 
  }

  public PvpTalentTiersData talent(IndexData talent) {
    
    this.talent = talent;
    return this;
  }

   /**
   * Get talent
   * @return talent
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public IndexData getTalent() {
    return talent;
  }


  public void setTalent(IndexData talent) {
    this.talent = talent;
  }


  public PvpTalentTiersData spellTooltip(PvpSpellDescritpionData spellTooltip) {
    
    this.spellTooltip = spellTooltip;
    return this;
  }

   /**
   * Get spellTooltip
   * @return spellTooltip
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public PvpSpellDescritpionData getSpellTooltip() {
    return spellTooltip;
  }


  public void setSpellTooltip(PvpSpellDescritpionData spellTooltip) {
    this.spellTooltip = spellTooltip;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PvpTalentTiersData pvpTalentTiersData = (PvpTalentTiersData) o;
    return Objects.equals(this.talent, pvpTalentTiersData.talent) &&
        Objects.equals(this.spellTooltip, pvpTalentTiersData.spellTooltip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(talent, spellTooltip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PvpTalentTiersData {\n");
    sb.append("    talent: ").append(toIndentedString(talent)).append("\n");
    sb.append("    spellTooltip: ").append(toIndentedString(spellTooltip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

