/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.3
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PveSpellDescritpionData } from './pveSpellDescritpionData';
import { TalentData } from './talentData';

/**
* PVE Talent data
*/
export class PveTalentData {
    /**
    * Id of the talent
    */
    'columnIndex'?: number;
    'talent'?: TalentData;
    'spellTooltip'?: PveSpellDescritpionData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "columnIndex",
            "baseName": "column_index",
            "type": "number"
        },
        {
            "name": "talent",
            "baseName": "talent",
            "type": "TalentData"
        },
        {
            "name": "spellTooltip",
            "baseName": "spell_tooltip",
            "type": "PveSpellDescritpionData"
        }    ];

    static getAttributeTypeMap() {
        return PveTalentData.attributeTypeMap;
    }
}

