/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PvpSpellDescritpionData } from './pvpSpellDescritpionData';
import { TalentData } from './talentData';

/**
* PVP Talent tiers data
*/
export class PvpTalentTiersData {
    'talent'?: TalentData;
    'spellTooltip'?: PvpSpellDescritpionData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "talent",
            "baseName": "talent",
            "type": "TalentData"
        },
        {
            "name": "spellTooltip",
            "baseName": "spell_tooltip",
            "type": "PvpSpellDescritpionData"
        }    ];

    static getAttributeTypeMap() {
        return PvpTalentTiersData.attributeTypeMap;
    }
}

