/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CharacterIndexData } from './characterIndexData';

/**
* Data of wow accounnt
*/
export class WowAccountData {
    /**
    * Id of the accounnt
    */
    'id': number;
    'characters': Array<CharacterIndexData>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "characters",
            "baseName": "characters",
            "type": "Array<CharacterIndexData>"
        }    ];

    static getAttributeTypeMap() {
        return WowAccountData.attributeTypeMap;
    }
}

