/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.IndexData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ArraySpecializationsIndexData
 */
public class ArraySpecializationsIndexDataTest {
    private final ArraySpecializationsIndexData model = new ArraySpecializationsIndexData();

    /**
     * Model tests for ArraySpecializationsIndexData
     */
    @Test
    public void testArraySpecializationsIndexData() {
        // TODO: test ArraySpecializationsIndexData
    }

    /**
     * Test the property 'characterSpecializations'
     */
    @Test
    public void characterSpecializationsTest() {
        // TODO: test characterSpecializations
    }

}
