/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.1
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.IndexData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CovenantProgressData
 */
public class CovenantProgressDataTest {
    private final CovenantProgressData model = new CovenantProgressData();

    /**
     * Model tests for CovenantProgressData
     */
    @Test
    public void testCovenantProgressData() {
        // TODO: test CovenantProgressData
    }

    /**
     * Test the property 'chosenCovenant'
     */
    @Test
    public void chosenCovenantTest() {
        // TODO: test chosenCovenant
    }

    /**
     * Test the property 'renownLevel'
     */
    @Test
    public void renownLevelTest() {
        // TODO: test renownLevel
    }

}
