/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.NameDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GenderNameDTO
 */
public class GenderNameDTOTest {
    private final GenderNameDTO model = new GenderNameDTO();

    /**
     * Model tests for GenderNameDTO
     */
    @Test
    public void testGenderNameDTO() {
        // TODO: test GenderNameDTO
    }

    /**
     * Test the property 'male'
     */
    @Test
    public void maleTest() {
        // TODO: test male
    }

    /**
     * Test the property 'female'
     */
    @Test
    public void femaleTest() {
        // TODO: test female
    }

}
