/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.GenderData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.IndexData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.PveTalentTiersData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.PvpTalentTiersData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.TypeData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlayableSpecializationData
 */
public class PlayableSpecializationDataTest {
    private final PlayableSpecializationData model = new PlayableSpecializationData();

    /**
     * Model tests for PlayableSpecializationData
     */
    @Test
    public void testPlayableSpecializationData() {
        // TODO: test PlayableSpecializationData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'playableClass'
     */
    @Test
    public void playableClassTest() {
        // TODO: test playableClass
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'genderDescription'
     */
    @Test
    public void genderDescriptionTest() {
        // TODO: test genderDescription
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'talentTiers'
     */
    @Test
    public void talentTiersTest() {
        // TODO: test talentTiers
    }

    /**
     * Test the property 'pvpTalents'
     */
    @Test
    public void pvpTalentsTest() {
        // TODO: test pvpTalents
    }

}
