/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.GenderNameDTO;
import fr.jbwittner.blizzardswagger.wowretailapi.model.IndexDTO;
import fr.jbwittner.blizzardswagger.wowretailapi.model.NameDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlayableClassDTO
 */
public class PlayableClassDTOTest {
    private final PlayableClassDTO model = new PlayableClassDTO();

    /**
     * Model tests for PlayableClassDTO
     */
    @Test
    public void testPlayableClassDTO() {
        // TODO: test PlayableClassDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'genderName'
     */
    @Test
    public void genderNameTest() {
        // TODO: test genderName
    }

    /**
     * Test the property 'powerType'
     */
    @Test
    public void powerTypeTest() {
        // TODO: test powerType
    }

    /**
     * Test the property 'specializations'
     */
    @Test
    public void specializationsTest() {
        // TODO: test specializations
    }

}
