/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.GenderData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.NameData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.TypeData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlayableRaceData
 */
public class PlayableRaceDataTest {
    private final PlayableRaceData model = new PlayableRaceData();

    /**
     * Model tests for PlayableRaceData
     */
    @Test
    public void testPlayableRaceData() {
        // TODO: test PlayableRaceData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'genderName'
     */
    @Test
    public void genderNameTest() {
        // TODO: test genderName
    }

    /**
     * Test the property 'faction'
     */
    @Test
    public void factionTest() {
        // TODO: test faction
    }

    /**
     * Test the property 'isSelectable'
     */
    @Test
    public void isSelectableTest() {
        // TODO: test isSelectable
    }

    /**
     * Test the property 'isAlliedRace'
     */
    @Test
    public void isAlliedRaceTest() {
        // TODO: test isAlliedRace
    }

}
