/*
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.jbwittner.blizzardswagger.wowretailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.jbwittner.blizzardswagger.wowretailapi.model.PveSpellDescritpionData;
import fr.jbwittner.blizzardswagger.wowretailapi.model.TalentData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PveTalentData
 */
public class PveTalentDataTest {
    private final PveTalentData model = new PveTalentData();

    /**
     * Model tests for PveTalentData
     */
    @Test
    public void testPveTalentData() {
        // TODO: test PveTalentData
    }

    /**
     * Test the property 'columnIndex'
     */
    @Test
    public void columnIndexTest() {
        // TODO: test columnIndex
    }

    /**
     * Test the property 'talent'
     */
    @Test
    public void talentTest() {
        // TODO: test talent
    }

    /**
     * Test the property 'spellTooltip'
     */
    @Test
    public void spellTooltipTest() {
        // TODO: test spellTooltip
    }

}
