/* tslint:disable */
/* eslint-disable */
/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IndexData } from './index-data';

/**
 * Array of classes index
 * @export
 * @interface ArrayClassesIndexData
 */
export interface ArrayClassesIndexData {
    /**
     * 
     * @type {Array<IndexData>}
     * @memberof ArrayClassesIndexData
     */
    'classes': Array<IndexData>;
}

