/* tslint:disable */
/* eslint-disable */
/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CovenantProgressData } from './covenant-progress-data';
import { GuildCharacterIndexData } from './guild-character-index-data';
import { IndexData } from './index-data';
import { RealmIndexData } from './realm-index-data';
import { TitleData } from './title-data';
import { TypeData } from './type-data';

/**
 * Character data
 * @export
 * @interface CharacterData
 */
export interface CharacterData {
    /**
     * 
     * @type {string}
     * @memberof CharacterData
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof CharacterData
     */
    'id': number;
    /**
     * 
     * @type {TypeData}
     * @memberof CharacterData
     */
    'gender': TypeData;
    /**
     * 
     * @type {TypeData}
     * @memberof CharacterData
     */
    'faction': TypeData;
    /**
     * 
     * @type {IndexData}
     * @memberof CharacterData
     */
    'race': IndexData;
    /**
     * 
     * @type {IndexData}
     * @memberof CharacterData
     */
    'character_class': IndexData;
    /**
     * 
     * @type {IndexData}
     * @memberof CharacterData
     */
    'active_spec': IndexData;
    /**
     * 
     * @type {RealmIndexData}
     * @memberof CharacterData
     */
    'realm': RealmIndexData;
    /**
     * 
     * @type {GuildCharacterIndexData}
     * @memberof CharacterData
     */
    'guild': GuildCharacterIndexData;
    /**
     * 
     * @type {number}
     * @memberof CharacterData
     */
    'level': number;
    /**
     * 
     * @type {number}
     * @memberof CharacterData
     */
    'experience': number;
    /**
     * 
     * @type {number}
     * @memberof CharacterData
     */
    'achievement_points': number;
    /**
     * 
     * @type {number}
     * @memberof CharacterData
     */
    'last_login_timestamp': number;
    /**
     * 
     * @type {number}
     * @memberof CharacterData
     */
    'average_item_level': number;
    /**
     * 
     * @type {number}
     * @memberof CharacterData
     */
    'equipped_item_level': number;
    /**
     * 
     * @type {TitleData}
     * @memberof CharacterData
     */
    'active_title': TitleData;
    /**
     * 
     * @type {CovenantProgressData}
     * @memberof CharacterData
     */
    'covenant_progress': CovenantProgressData;
}

