/* tslint:disable */
/* eslint-disable */
/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.1
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RealmIndexData } from './realm-index-data';
import { TypeData } from './type-data';

/**
 * Index of guild character
 * @export
 * @interface GuildCharacterIndexData
 */
export interface GuildCharacterIndexData {
    /**
     * 
     * @type {string}
     * @memberof GuildCharacterIndexData
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof GuildCharacterIndexData
     */
    'id': number;
    /**
     * 
     * @type {RealmIndexData}
     * @memberof GuildCharacterIndexData
     */
    'realm': RealmIndexData;
    /**
     * 
     * @type {TypeData}
     * @memberof GuildCharacterIndexData
     */
    'faction': TypeData;
}

