/* tslint:disable */
/* eslint-disable */
/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GenderData } from './gender-data';
import { NameData } from './name-data';
import { TypeData } from './type-data';

/**
 * Playable race data
 * @export
 * @interface PlayableRaceData
 */
export interface PlayableRaceData {
    /**
     * Id of the race
     * @type {number}
     * @memberof PlayableRaceData
     */
    'id': number;
    /**
     * 
     * @type {NameData}
     * @memberof PlayableRaceData
     */
    'name': NameData;
    /**
     * 
     * @type {GenderData}
     * @memberof PlayableRaceData
     */
    'gender_name': GenderData;
    /**
     * 
     * @type {TypeData}
     * @memberof PlayableRaceData
     */
    'faction': TypeData;
    /**
     * 
     * @type {boolean}
     * @memberof PlayableRaceData
     */
    'is_selectable': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlayableRaceData
     */
    'is_allied_race': boolean;
}

