/* tslint:disable */
/* eslint-disable */
/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.1
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GenderData } from './gender-data';
import { IndexData } from './index-data';
import { NameData } from './name-data';

/**
 * Playable class data
 * @export
 * @interface PlayableClassData
 */
export interface PlayableClassData {
    /**
     * Id of the class
     * @type {number}
     * @memberof PlayableClassData
     */
    'id': number;
    /**
     * 
     * @type {NameData}
     * @memberof PlayableClassData
     */
    'name': NameData;
    /**
     * 
     * @type {GenderData}
     * @memberof PlayableClassData
     */
    'gender_name': GenderData;
    /**
     * 
     * @type {IndexData}
     * @memberof PlayableClassData
     */
    'power_type': IndexData;
    /**
     * 
     * @type {Array<IndexData>}
     * @memberof PlayableClassData
     */
    'specializations': Array<IndexData>;
}

