/* tslint:disable */
/* eslint-disable */
/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Description of the pvp spell
 * @export
 * @interface PvpSpellDescritpionData
 */
export interface PvpSpellDescritpionData {
    /**
     * 
     * @type {object}
     * @memberof PvpSpellDescritpionData
     */
    'description': object;
    /**
     * 
     * @type {object}
     * @memberof PvpSpellDescritpionData
     */
    'cast_time': object;
}

