/* tslint:disable */
/* eslint-disable */
/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PvpSpellDescritpionData } from './pvp-spell-descritpion-data';
import { TalentData } from './talent-data';

/**
 * PVP Talent tiers data
 * @export
 * @interface PvpTalentTiersData
 */
export interface PvpTalentTiersData {
    /**
     * 
     * @type {TalentData}
     * @memberof PvpTalentTiersData
     */
    'talent'?: TalentData;
    /**
     * 
     * @type {PvpSpellDescritpionData}
     * @memberof PvpTalentTiersData
     */
    'spell_tooltip'?: PvpSpellDescritpionData;
}

