/* tslint:disable */
/* eslint-disable */
/**
 * Swagger BLIZZARD Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.1
 * Contact: jeanbaptiste.wittner@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NameData } from './name-data';

/**
 * Index of realm
 * @export
 * @interface RealmIndexData
 */
export interface RealmIndexData {
    /**
     * Id of the index
     * @type {number}
     * @memberof RealmIndexData
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof RealmIndexData
     */
    'slug': string;
    /**
     * 
     * @type {NameData}
     * @memberof RealmIndexData
     */
    'name': NameData;
}

